### ISSUE TITLE
Unable to edit User Group as while logged in as root user

### ISSUE THREAD

**Issue by fstaylor104** [alexweissman/UserFrosting#383]
Hi guys, whenever I sign in as the root user and go to edit my user group landing page I get a warning to check the php error logs which outputs as follows:

```
[03-Aug-2015 07:10:34 America/New_York] Error in C:\wamp\www\Project\userfrosting\userfrosting\models\mysql\MySqlGroup.php on line 23: Object of class UserFrosting\DatabaseTable could not be converted to string

[03-Aug-2015 07:10:34 America/New_York] #0 C:\wamp\www\Project\userfrosting\userfrosting\models\mysql\MySqlGroup.php(23): Slim\Slim::handleErrors(4096, 'Object of class...', 'C:\\wamp\\www\\Pro...', 23, Array)
#1 C:\wamp\www\Project\userfrosting\userfrosting\controllers\GroupController.php(321): UserFrosting\MySqlGroup->store()
#2 C:\wamp\www\Project\userfrosting\public\index.php(206): UserFrosting\GroupController->updateGroup('1')
#3 [internal function]: {closure}('1')
#4 C:\wamp\www\Project\userfrosting\userfrosting\vendor\slim\slim\Slim\Route.php(468): call_user_func_array(Object(Closure), Array)
#5 C:\wamp\www\Project\userfrosting\userfrosting\vendor\slim\slim\Slim\Slim.php(1357): Slim\Route->dispatch()
#6 C:\wamp\www\Project\userfrosting\userfrosting\vendor\slim\slim\Slim\Middleware\Flash.php(85): Slim\Slim->call()
#7 C:\wamp\www\Project\userfrosting\userfrosting\vendor\slim\slim\Slim\Middleware\MethodOverride.php(92): Slim\Middleware\Flash->call()
#8 C:\wamp\www\Project\userfrosting\userfrosting\auth\CsrfGuard.php(51): Slim\Middleware\MethodOverride->call()
#9 C:\wamp\www\Project\userfrosting\userfrosting\vendor\slim\slim\Slim\Slim.php(1302): Slim\Extras\Middleware\CsrfGuard->call()
#10 C:\wamp\www\Project\userfrosting\public\index.php(388): Slim\Slim->run()
#11 {main}
```

Any ideas on how to fix this issue would be greatly appreciated!

Many Thanks!

**Comment by alexweissman** [comment]
Looks like a bug to me in https://github.com/alexweissman/UserFrosting/blob/master/userfrosting/models/mysql/MySqlGroup.php#L23.  I'll get it fixed, thanks for finding it!

**Comment by alexweissman** [comment]
Ok, should be fixed.  Please let me know if this resolves your issue.

**Comment by fstaylor104** [comment]
Alex,

Got it working, but had to change user from default primary to default...
Many Thanks!

**Comment by alexweissman** [comment]
No problem!

**Comment by tolotratlt** [comment]
I had the same problem too, but now it is set. Thank you so much

**Comment by alexweissman** [comment]
No problem, don't forget to star the project!
